import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Layouts/Header";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import { blunext, dosis, crimsonText, sfProBold, sfProDisplay, sfProMedium } from "../../public/font/font";
import Footer from "@/components/Layouts/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${blunext.variable} ${dosis.variable} ${crimsonText.variable} ${sfProBold.variable} ${sfProDisplay.variable} ${sfProMedium.variable}`}>
        <body>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}

